### ISSUE TITLE
feat: allow negative chat_id, which means group chats

### ISSUE THREAD

**Issue by freinbichler** [JakobLichterfeld/TeslaMate-Telegram-Bot#35]
After upgrading to v0.7.3 I am now getting this error:

`ERROR - Error: Please set the environment variable TELEGRAM_BOT_CHAT_ID to a valid number and try again.`

My env variable:

`TELEGRAM_BOT_CHAT_ID=-410996XXX`

XXX are more digits, removed for privacy. I guess the issue is that it is a negative number. Also doesn't work if I wrap it in double quotes.

**Comment by JakobLichterfeld** [comment]
Thanks for reporting. All chat_ids I came across were positive numberic, that's why I implemented the check that way. Anyway, seems like no more releases after just 3 hours of sleep.

**Comment by JakobLichterfeld** [comment]
Negative chat_id means group chat

**Comment by freinbichler** [comment]
Would still be great to allow negative ids aka group chats, because that is where I used the bot until now
