### ISSUE TITLE
Question, Not an Issue

### ISSUE THREAD

**Issue by stauffenberg2020** [JakobLichterfeld/TeslaMate-Telegram-Bot#41]
Hi @JakobLichterfeld,

Can you please let me know how different this notification is when compared to the official Tesla app sending a notification about an available update?

**Comment by JakobLichterfeld** [comment]
Hi,
The official Tesla APP notifies you when a firmware update has been downloaded from your car and is ready to install.

If your car is not parked near a WiFi, you will only be notified in the rare case that the update is so urgent that it was downloaded over LTE.

TeslaMate Telegram Bot notifes you, when a firmware update **is available** so you can either bring WiFi to your car or your car to WiFi.

**Comment by JakobLichterfeld** [comment]
Tesla API sends whether an update is available for your car and its version. TeslaMate receives this information and populates via MQTT which is consumed by TeslaMate Telegram Bot which then sends a Telegram message to you.
TeslaMate do not wake your car, just consumes and TeslaMate Telegram Bot just listen to the MQTT messages from TeslaMate. So to answer your question in one word: no.

Btw: With publicly available information, your assumptions are wrong.
